version: "3"

services:
  webserver:
    image: "chl9159/sdc"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql1
    links:
      - mysql1

  mysql1:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "chris"
      MYSQL_USER: "root"
      MYSQL_ROOT_HOST: '%'
    restart: always
    expose: 
      - "3306"
    ports: 
      - "3306:3306"
