version: "3"

services:
  webserver:
    image: ""
    restart: always
    ports:
      - "3000:3000"
    # volumes:
    #   - ./websites:/user/share/node/html
    depends_on:
      - mysql_db
    links:
      - mysql_db

  mysql_db:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD="chris"
    restart: always
    ports: "3306:3306"
    # volumes:
    #   - db_vol:/var/lib/mysql
  
# volumes:
#   - db_vol:
