version: "3"

services:
  webserver:
    image: "chl9159/sdc"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
    links:
      - mysql_db

  mysql_db:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD="chris"
      - MYSQL_ROOT_HOST=%
    restart: always
    ports: 
      - "3307:3306"
